u-boot: quartz64 fixed booting
U-Boot SPL board init
U-Boot SPL 2017.09-rk3566 (Mar 24 2022 - 09:32:12)
unknown raw ID phN
unrecognized JEDEC id bytes: 00, 00, 00
Trying to boot from MMC2
Jumping to U-Boot(0x00a00000) via ARM Trusted Firmware(0x00040000)
Total: 225.71 ms

INFO:    Preloader serial: 2
NOTICE:  BL31: v2.3():v2.3-135-gcda1658bc-dirty:xsf
NOTICE:  BL31: Built : 14:19:26, Jun  1 2021
INFO:    GICv3 without legacy support detected.
INFO:    ARM GICv3 driver initialized in EL3
INFO:    pmu v1 is valid
INFO:    dfs DDR fsp_param[0].freq_mhz= 1056MHz
INFO:    dfs DDR fsp_param[1].freq_mhz= 324MHz
INFO:    dfs DDR fsp_param[2].freq_mhz= 528MHz
INFO:    dfs DDR fsp_param[3].freq_mhz= 780MHz
INFO:    Using opteed sec cpu_context!
INFO:    boot cpu mask: 0
INFO:    BL31: Initializing runtime services
WARNING: No OPTEE provided by BL2 boot loader, Booting device without OPTEE initialization. SMC`s destined for OPTEE will return SMC_UNK
ERROR:   Error initializing runtime service opteed_fast
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0xa00000
INFO:    SPSR = 0x3c9

U-Boot 2017.09-rk3566 (Mar 24 2022 - 09:34:06 +0200)

Model: Pine64 RK3566 Quartz64 Board
PreSerial: 2, raw, 0xfe660000
DRAM:  7.7 GiB
Sysmem: init
Relocation Offset: ed357000, fdt: eb9f94f8
Using default environment

no mmc device at slot 1
dwmms@fe2b0000: 1 (SD), dwmmc@fe2c0000: 2, sdhci@fe310000: 0
Bootdev(atags): mmc 1
MMC1: Legacy, 50Mhz
PartType: DOS
No misc partition
boot mode: None
FIT: No boot partition
No resource partition
Failed to load DTB
Failed to get kernel dtb, ret=-19
io-domain: OK
Model: Pine64 RK3566 Quartz64 Board
rockchip_set_serialno: could not find efuse/otp device
CLK: (sync kernel. arm: enter 816000 KHz, init 816000 KHz, kernel 0N/A)
  apll 816000 KHz
  dpll 528000 KHz
  gpll 1188000 KHz
  cpll 1000000 KHz
  npll 24000 KHz
  vpll 24000 KHz
  hpll 24000 KHz
  ppll 100000 KHz
  armclk 816000 KHz
  aclk_bus 150000 KHz
  pclk_bus 50000 KHz
  aclk_top_high 300000 KHz
  aclk_top_low 200000 KHz
  hclk_top 150000 KHz
  pclk_top 50000 KHz
  aclk_perimid 300000 KHz
  hclk_perimid 150000 KHz
  pclk_pmu 50000 KHz
Net:   clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
Hit key to stop autoboot('CTRL+C'):  0
switch to partitions #0, OK
mmc1 is current device
Failed to mount ext2 filesystem...
** Unrecognized filesystem type **
MMC error: The cmd index is 0, ret is -110
mmc_init: -110, time 5
starting USB...
Bus dwc3@fcc00000: usb maximum-speed not found
Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
Bus dwc3@fd000000: usb maximum-speed not found
Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
scanning bus dwc3@fcc00000 for devices... 1 USB Device(s) found
scanning bus dwc3@fd000000 for devices... 9>USr>fevise.s)>founf��>>>>.  scanning usb for storage devices... 0 Storage Device(s) found

Device 0: unknown device
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: pxeuuid
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00000000
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0000000
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/000000
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00000
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0000
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/000
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm-rockchip
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22Config file not found
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22No ethernet found.
clk_get_by_name(master_bus) failed: -22eqos_probe_resources() failed: -22## Booting FIT Image FIT: No boot partition
FIT: No FIT image
MMC error: The cmd index is 0, ret is -110
mmc_init: -110, time 5
Could not get mmc 0
=>